In [1]:
import sys
sys.path.append('../')
from SGD import custom_SGD

In [2]:
custom_SGD.grad_logit_step_test()

X values 
[[1. 4. 7.]
 [1. 2. 6.]]
Iter 0 theta: [ 0.79204728 -0.17385816 -1.12669268]
Training Accuracy: 0.500
Iter 1 theta: [1.24104927 1.62377359 2.01713315]
Training Accuracy: 0.500
Iter 2 theta: [ 0.7910493   0.72377365 -0.68286668]
Training Accuracy: 0.500
Iter 3 theta: [1.06746351 1.9508098  1.31272243]
Training Accuracy: 0.500
Iter 4 theta: [ 0.6174647  1.0508122 -1.3872704]
Training Accuracy: 0.500
Iter 5 theta: [1.06245549 2.83407623 1.72931556]
Training Accuracy: 0.500
Iter 6 theta: [ 0.61245551  1.93407626 -0.97068434]
Training Accuracy: 1.000
Iter 7 theta: [ 0.5978657   2.06195888 -0.97969209]
Training Accuracy: 1.000
Iter 8 theta: [ 0.54438596  2.06343483 -1.24635281]
Training Accuracy: 1.000
Iter 9 theta: [0.7354739  2.87904569 0.11689236]
Training Accuracy: 0.500
Iter 10 theta: [ 0.28581227  1.97972433 -2.58107647]
Training Accuracy: 0.500
Iter 11 theta: [0.73578294 3.77961879 0.56872407]
Training Accuracy: 0.500
Iter 12 theta: [ 0.28578664  2.8796262  -2.13125369]
Trai

In [3]:
custom_SGD.SGD_test()

X values 
[[1.799e+01 2.066e+01 1.178e+02 ... 1.974e-01 3.060e-01 8.503e-02]
 [2.029e+01 1.434e+01 1.351e+02 ... 1.625e-01 2.364e-01 7.678e-02]
 [9.000e+00 1.440e+01 5.636e+01 ... 1.389e-02 2.991e-01 7.804e-02]
 ...
 [1.720e+01 2.452e+01 1.142e+02 ... 1.899e-01 3.313e-01 1.339e-01]
 [1.403e+01 2.125e+01 8.979e+01 ... 7.963e-02 2.226e-01 7.617e-02]
 [1.303e+01 1.842e+01 8.261e+01 ... 5.013e-02 1.987e-01 6.169e-02]]

Full batch
Number of samples: 455
Number of parameters: 31
It: 1 Batch: 1 Epoch 0 Train Acc : 0.37362637 lr: 0.01000000 
It: 100 Batch: 1 Epoch 99 Train Acc : 0.37802198 lr: 0.01000000 
It: 200 Batch: 1 Epoch 199 Train Acc : 0.87472527 lr: 0.01000000 
It: 300 Batch: 1 Epoch 299 Train Acc : 0.88351648 lr: 0.01000000 


/notebooks/local/LogisticRegression-ANN/SGD/custom_SGD.py:98: RuntimeWarning: overflow encountered in exp
  h = 1 / (1 + np.exp(-dot))


It: 400 Batch: 1 Epoch 399 Train Acc : 0.84175824 lr: 0.01000000 
It: 500 Batch: 1 Epoch 499 Train Acc : 0.90109890 lr: 0.01000000 
It: 600 Batch: 1 Epoch 599 Train Acc : 0.89450549 lr: 0.01000000 
It: 700 Batch: 1 Epoch 699 Train Acc : 0.89230769 lr: 0.01000000 
It: 800 Batch: 1 Epoch 799 Train Acc : 0.88351648 lr: 0.01000000 
It: 900 Batch: 1 Epoch 899 Train Acc : 0.86373626 lr: 0.01000000 
It: 1000 Batch: 1 Epoch 999 Train Acc : 0.89670330 lr: 0.01000000 
It: 1100 Batch: 1 Epoch 1099 Train Acc : 0.91208791 lr: 0.01000000 
It: 1200 Batch: 1 Epoch 1199 Train Acc : 0.91428571 lr: 0.01000000 
It: 1300 Batch: 1 Epoch 1299 Train Acc : 0.91648352 lr: 0.01000000 
It: 1400 Batch: 1 Epoch 1399 Train Acc : 0.92087912 lr: 0.01000000 
It: 1500 Batch: 1 Epoch 1499 Train Acc : 0.92307692 lr: 0.01000000 
It: 1600 Batch: 1 Epoch 1599 Train Acc : 0.92087912 lr: 0.01000000 
It: 1700 Batch: 1 Epoch 1699 Train Acc : 0.74065934 lr: 0.01000000 
It: 1800 Batch: 1 Epoch 1799 Train Acc : 0.90989011 lr: 0.010

It: 2500 Batch: 5 Epoch 499 Train Acc : 0.78181818 lr: 0.01000000 
It: 2600 Batch: 5 Epoch 519 Train Acc : 0.89090909 lr: 0.01000000 
It: 2700 Batch: 5 Epoch 539 Train Acc : 0.78181818 lr: 0.01000000 
It: 2800 Batch: 5 Epoch 559 Train Acc : 0.89090909 lr: 0.01000000 
It: 2900 Batch: 5 Epoch 579 Train Acc : 0.92727273 lr: 0.01000000 
It: 3000 Batch: 5 Epoch 599 Train Acc : 0.85454545 lr: 0.01000000 
It: 3100 Batch: 5 Epoch 619 Train Acc : 0.92727273 lr: 0.01000000 
It: 3200 Batch: 5 Epoch 639 Train Acc : 0.94545455 lr: 0.01000000 
It: 3300 Batch: 5 Epoch 659 Train Acc : 0.81818182 lr: 0.01000000 
It: 3400 Batch: 5 Epoch 679 Train Acc : 0.90909091 lr: 0.01000000 
It: 3500 Batch: 5 Epoch 699 Train Acc : 0.69090909 lr: 0.01000000 
It: 3600 Batch: 5 Epoch 719 Train Acc : 0.92727273 lr: 0.01000000 
It: 3700 Batch: 5 Epoch 739 Train Acc : 0.87272727 lr: 0.01000000 
It: 3800 Batch: 5 Epoch 759 Train Acc : 0.85454545 lr: 0.01000000 
It: 3900 Batch: 5 Epoch 779 Train Acc : 0.78181818 lr: 0.01000

It: 6200 Batch: 5 Epoch 1239 Train Acc : 0.92727273 lr: 0.01000000 
It: 6300 Batch: 5 Epoch 1259 Train Acc : 0.92727273 lr: 0.01000000 
It: 6400 Batch: 5 Epoch 1279 Train Acc : 0.92727273 lr: 0.01000000 
It: 6500 Batch: 5 Epoch 1299 Train Acc : 0.92727273 lr: 0.01000000 
It: 6600 Batch: 5 Epoch 1319 Train Acc : 0.92727273 lr: 0.01000000 
It: 6700 Batch: 5 Epoch 1339 Train Acc : 0.89090909 lr: 0.01000000 
It: 6800 Batch: 5 Epoch 1359 Train Acc : 0.90909091 lr: 0.01000000 
It: 6900 Batch: 5 Epoch 1379 Train Acc : 0.92727273 lr: 0.01000000 
It: 7000 Batch: 5 Epoch 1399 Train Acc : 0.92727273 lr: 0.01000000 
It: 7100 Batch: 5 Epoch 1419 Train Acc : 0.90909091 lr: 0.01000000 
It: 7200 Batch: 5 Epoch 1439 Train Acc : 0.92727273 lr: 0.01000000 
It: 7300 Batch: 5 Epoch 1459 Train Acc : 0.92727273 lr: 0.01000000 
It: 7400 Batch: 5 Epoch 1479 Train Acc : 0.90909091 lr: 0.01000000 
It: 7500 Batch: 5 Epoch 1499 Train Acc : 0.90909091 lr: 0.01000000 
It: 7600 Batch: 5 Epoch 1519 Train Acc : 0.92727

It: 8300 Batch: 110 Epoch 18 Train Acc : 1.00000000 lr: 0.01000000 
It: 8400 Batch: 210 Epoch 18 Train Acc : 1.00000000 lr: 0.01000000 
It: 8500 Batch: 310 Epoch 18 Train Acc : 1.00000000 lr: 0.01000000 
It: 8600 Batch: 410 Epoch 18 Train Acc : 1.00000000 lr: 0.01000000 
It: 8700 Batch: 55 Epoch 19 Train Acc : 1.00000000 lr: 0.01000000 
It: 8800 Batch: 155 Epoch 19 Train Acc : 1.00000000 lr: 0.01000000 
It: 8900 Batch: 255 Epoch 19 Train Acc : 1.00000000 lr: 0.01000000 
It: 9000 Batch: 355 Epoch 19 Train Acc : 1.00000000 lr: 0.01000000 
It: 9100 Batch: 455 Epoch 19 Train Acc : 1.00000000 lr: 0.01000000 
It: 9200 Batch: 100 Epoch 20 Train Acc : 1.00000000 lr: 0.01000000 
It: 9300 Batch: 200 Epoch 20 Train Acc : 1.00000000 lr: 0.01000000 
It: 9400 Batch: 300 Epoch 20 Train Acc : 1.00000000 lr: 0.01000000 
It: 9500 Batch: 400 Epoch 20 Train Acc : 1.00000000 lr: 0.01000000 
It: 9600 Batch: 45 Epoch 21 Train Acc : 1.00000000 lr: 0.01000000 
It: 9700 Batch: 145 Epoch 21 Train Acc : 1.0000000