In [1]:
import sys
sys.path.append('../')
from SGD import custom_SGD

In [2]:
custom_SGD.grad_logit_step_test()

X values 
[[1. 4. 7.]
 [1. 2. 6.]]
Iter 0 theta: [ 0.79204728 -0.17385816 -1.12669268]
RMSE error: 0.7068
Iter 1 theta: [1.24104927 1.62377359 2.01713315]
RMSE error: 0.7071
Iter 2 theta: [ 0.7910493   0.72377365 -0.68286668]
RMSE error: 0.5382
Iter 3 theta: [1.06746351 1.9508098  1.31272243]
RMSE error: 0.7071
Iter 4 theta: [ 0.6174647  1.0508122 -1.3872704]
RMSE error: 0.7018
Iter 5 theta: [1.06245549 2.83407623 1.72931556]
RMSE error: 0.7071
Iter 6 theta: [ 0.61245551  1.93407626 -0.97068434]
RMSE error: 0.1914
Iter 7 theta: [ 0.5978657   2.06195888 -0.97969209]
RMSE error: 0.1895
Iter 8 theta: [ 0.54438596  2.06343483 -1.24635281]
RMSE error: 0.3429
Iter 9 theta: [0.7354739  2.87904569 0.11689236]
RMSE error: 0.7066
Iter 10 theta: [ 0.28581227  1.97972433 -2.58107647]
RMSE error: 0.7071
Iter 11 theta: [0.73578294 3.77961879 0.56872407]
RMSE error: 0.7071
Iter 12 theta: [ 0.28578664  2.8796262  -2.13125369]
RMSE error: 0.6770
Iter 13 theta: [0.71612522 4.602041   0.8816466 ]
RMSE er

In [3]:
custom_SGD.SGD_test()

X values 
[[1.799e+01 2.066e+01 1.178e+02 ... 1.974e-01 3.060e-01 8.503e-02]
 [2.029e+01 1.434e+01 1.351e+02 ... 1.625e-01 2.364e-01 7.678e-02]
 [9.000e+00 1.440e+01 5.636e+01 ... 1.389e-02 2.991e-01 7.804e-02]
 ...
 [1.720e+01 2.452e+01 1.142e+02 ... 1.899e-01 3.313e-01 1.339e-01]
 [1.403e+01 2.125e+01 8.979e+01 ... 7.963e-02 2.226e-01 7.617e-02]
 [1.303e+01 1.842e+01 8.261e+01 ... 5.013e-02 1.987e-01 6.169e-02]]

Full batch
Number of samples: 455
Number of parameters: 31
It: 1 Batch: 1 Epoch 0 Error: 0.31318681 lr: 0.01000000 
It: 1000 Batch: 1 Epoch 999 Error: 0.05174280 lr: 0.01000000 


/notebooks/local/LogisticRegression-ANN/SGD/custom_SGD.py:95: RuntimeWarning: overflow encountered in exp
  h = 1 / (1 + np.exp(-dot))


It: 2000 Batch: 1 Epoch 1999 Error: 0.04284557 lr: 0.01000000 
It: 3000 Batch: 1 Epoch 2999 Error: 0.04811405 lr: 0.01000000 
It: 4000 Batch: 1 Epoch 3999 Error: 0.04395628 lr: 0.01000000 
It: 5000 Batch: 1 Epoch 4999 Error: 0.04285718 lr: 0.01000000 
It: 6000 Batch: 1 Epoch 5999 Error: 0.12857143 lr: 0.01000000 
It: 7000 Batch: 1 Epoch 6999 Error: 0.04393103 lr: 0.01000000 
It: 8000 Batch: 1 Epoch 7999 Error: 0.04938446 lr: 0.01000000 
It: 9000 Batch: 1 Epoch 8999 Error: 0.03736264 lr: 0.01000000 
It: 10000 Batch: 1 Epoch 9999 Error: 0.03516484 lr: 0.01000000 
Finished 
 It: 10000 Batch: 1 Epoch 9999 Train Loss: 0.03516484 lr: 0.01000000 
finished  14.412104868999998
Accuracy: 0.842
Precision: 0.899
Recall: 1.000

Stochastic Mini batch
Number of samples: 455
Number of parameters: 31
Shuffled
It: 1 Batch: 1 Epoch 0 Error: 0.33000000 lr: 0.01000000 
It: 1000 Batch: 5 Epoch 199 Error: 0.03636364 lr: 0.01000000 
Finished 
 It: 1470 Batch: 5 Epoch 293 Train Loss: 0.00000000 lr: 0.01000000 

TypeError: unorderable types: int() > NoneType()